language: php

php:
  - 5.3

mysql:
  database: biological_taxonomy_test
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql php5-sqlite
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # install drush globally
  - composer global require drush/drush:6.*

before_script:
  - cd ../..
  - mysql -e 'create database biological_taxonomy_test'
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/biological_taxonomy_test --enable=simpletest biological_taxonomy_test

  - ln -s $(readlink -e $(cd -)) biological_taxonomy_test/drupal/sites/all/modules/biological_taxonomy
  - cd biological_taxonomy_test/drupal
  - drush --yes pm-enable biological_taxonomy
  - mkdir --parents sites/all/libraries/itis
  - touch sites/all/libraries/itis/ITIS.sqlite
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run 'Biological Taxonomy' --uri=http://127.0.0.1:8080

