<?php

/**
 * @file
 * Create a structured biological taxonomy from an ITIS database.
 */

/**
 * Implements hook_menu().
 */
function biological_taxonomy_menu() {
  $items = array();

  $items['admin/config/biological_taxonomy'] = array(
    'title' => 'Biological Taxonomy',
    'description' => 'Parent menu item for biological taxonomy menus.',
    'position' => 'right',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/biological_taxonomy/build'] = array(
    'title' => 'Create a Biological Taxonomy',
    'description' => 'Build a biological taxonomy from an ITIS database.',
    'page callback' => '_biological_taxonomy_render_admin_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'forms/biological_taxonomy_build.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function biological_taxonomy_libraries_info() {
  $libraries = array();

  $libraries['itis'] = array(
    'name' => t('ITIS Data File'),
    'vendor url' => 'http://www.itis.gov/downloads/',
    'download url' => 'http://www.itis.gov/downloads/itisSqlite.zip',
    'version callback' => '_biological_taxonomy_check_itis_valid',
    'files' => array(
      'js' => array(
        'ITIS.sqlite',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_help().
 */
function biological_taxonomy_help($path, $arg) {
  switch ($path) {
    case 'admin/help#biological_taxonomy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides functionality to build a hierarchical biological taxonomy sourced from the <a href="@itisurl">ITIS database</a>.', array('@itisurl' => 'http://www.itis.gov/')) . '</p>';
      $output .= '<p>' . t('Depending on the options selected, the created taxonomy could be enormous. Extremely large taxonomies can have adverse effects on Drupal.') . '</p>';
      $output .= '<p>' . t('As with all hierarchical taxonomy trees, a module such as <a href="@taxman">taxonomy_manager</a> is recommended for use in managing the resultant vocabulary.', array('@taxman' => 'https://www.drupal.org/project/taxonomy_manager')) . '</p>';
      $output .= '<h3>' . t('Installation') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Download the Full ITIS Data Set SQLite database (<a href="@itis">@itis</a>) and extract the <em>ITIS.sqlite</em> file into <em>/sites/all/libraries/itis/</em>.</li>', array('@itis' => 'http://www.itis.gov/downloads/')) . '</li>';
      $output .= '<li>' . t('Enable the module, then browse to <a href="/@bioadminpath">@bioadminpath</a>', array('@bioadminpath' => 'admin/config/biological_taxonomy/build')) . '</li>';
      $output .= '</ol>';
      return $output;
  }
}
